# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/feniks/my_ws/studia/6sem/wds/space-invaders-sdv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/feniks/my_ws/studia/6sem/wds/space-invaders-sdv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feniks/my_ws/studia/6sem/wds/space-invaders-sdv/CMakeFiles /home/feniks/my_ws/studia/6sem/wds/space-invaders-sdv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feniks/my_ws/studia/6sem/wds/space-invaders-sdv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SpaceInvaders

# Build rule for target.
SpaceInvaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpaceInvaders
.PHONY : SpaceInvaders

# fast build rule for target.
SpaceInvaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/build
.PHONY : SpaceInvaders/fast

#=============================================================================
# Target rules for targets named SpaceInvaders_autogen_timestamp_deps

# Build rule for target.
SpaceInvaders_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpaceInvaders_autogen_timestamp_deps
.PHONY : SpaceInvaders_autogen_timestamp_deps

# fast build rule for target.
SpaceInvaders_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders_autogen_timestamp_deps.dir/build.make CMakeFiles/SpaceInvaders_autogen_timestamp_deps.dir/build
.PHONY : SpaceInvaders_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SpaceInvaders_autogen

# Build rule for target.
SpaceInvaders_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpaceInvaders_autogen
.PHONY : SpaceInvaders_autogen

# fast build rule for target.
SpaceInvaders_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders_autogen.dir/build.make CMakeFiles/SpaceInvaders_autogen.dir/build
.PHONY : SpaceInvaders_autogen/fast

SpaceInvaders_autogen/EWIEGA46WW/qrc_res.o: SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.o
.PHONY : SpaceInvaders_autogen/EWIEGA46WW/qrc_res.o

# target to build an object file
SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.o
.PHONY : SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.o

SpaceInvaders_autogen/EWIEGA46WW/qrc_res.i: SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.i
.PHONY : SpaceInvaders_autogen/EWIEGA46WW/qrc_res.i

# target to preprocess a source file
SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.i
.PHONY : SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.i

SpaceInvaders_autogen/EWIEGA46WW/qrc_res.s: SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.s
.PHONY : SpaceInvaders_autogen/EWIEGA46WW/qrc_res.s

# target to generate assembly for a file
SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.s
.PHONY : SpaceInvaders_autogen/EWIEGA46WW/qrc_res.cpp.s

SpaceInvaders_autogen/mocs_compilation.o: SpaceInvaders_autogen/mocs_compilation.cpp.o
.PHONY : SpaceInvaders_autogen/mocs_compilation.o

# target to build an object file
SpaceInvaders_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpaceInvaders_autogen/mocs_compilation.cpp.o
.PHONY : SpaceInvaders_autogen/mocs_compilation.cpp.o

SpaceInvaders_autogen/mocs_compilation.i: SpaceInvaders_autogen/mocs_compilation.cpp.i
.PHONY : SpaceInvaders_autogen/mocs_compilation.i

# target to preprocess a source file
SpaceInvaders_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpaceInvaders_autogen/mocs_compilation.cpp.i
.PHONY : SpaceInvaders_autogen/mocs_compilation.cpp.i

SpaceInvaders_autogen/mocs_compilation.s: SpaceInvaders_autogen/mocs_compilation.cpp.s
.PHONY : SpaceInvaders_autogen/mocs_compilation.s

# target to generate assembly for a file
SpaceInvaders_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpaceInvaders_autogen/mocs_compilation.cpp.s
.PHONY : SpaceInvaders_autogen/mocs_compilation.cpp.s

src/AxisPlot.o: src/AxisPlot.cpp.o
.PHONY : src/AxisPlot.o

# target to build an object file
src/AxisPlot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/AxisPlot.cpp.o
.PHONY : src/AxisPlot.cpp.o

src/AxisPlot.i: src/AxisPlot.cpp.i
.PHONY : src/AxisPlot.i

# target to preprocess a source file
src/AxisPlot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/AxisPlot.cpp.i
.PHONY : src/AxisPlot.cpp.i

src/AxisPlot.s: src/AxisPlot.cpp.s
.PHONY : src/AxisPlot.s

# target to generate assembly for a file
src/AxisPlot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/AxisPlot.cpp.s
.PHONY : src/AxisPlot.cpp.s

src/Bullet.o: src/Bullet.cpp.o
.PHONY : src/Bullet.o

# target to build an object file
src/Bullet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Bullet.cpp.o
.PHONY : src/Bullet.cpp.o

src/Bullet.i: src/Bullet.cpp.i
.PHONY : src/Bullet.i

# target to preprocess a source file
src/Bullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Bullet.cpp.i
.PHONY : src/Bullet.cpp.i

src/Bullet.s: src/Bullet.cpp.s
.PHONY : src/Bullet.s

# target to generate assembly for a file
src/Bullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Bullet.cpp.s
.PHONY : src/Bullet.cpp.s

src/ComboBoxTxt.o: src/ComboBoxTxt.cpp.o
.PHONY : src/ComboBoxTxt.o

# target to build an object file
src/ComboBoxTxt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/ComboBoxTxt.cpp.o
.PHONY : src/ComboBoxTxt.cpp.o

src/ComboBoxTxt.i: src/ComboBoxTxt.cpp.i
.PHONY : src/ComboBoxTxt.i

# target to preprocess a source file
src/ComboBoxTxt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/ComboBoxTxt.cpp.i
.PHONY : src/ComboBoxTxt.cpp.i

src/ComboBoxTxt.s: src/ComboBoxTxt.cpp.s
.PHONY : src/ComboBoxTxt.s

# target to generate assembly for a file
src/ComboBoxTxt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/ComboBoxTxt.cpp.s
.PHONY : src/ComboBoxTxt.cpp.s

src/ControllerManager.o: src/ControllerManager.cpp.o
.PHONY : src/ControllerManager.o

# target to build an object file
src/ControllerManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/ControllerManager.cpp.o
.PHONY : src/ControllerManager.cpp.o

src/ControllerManager.i: src/ControllerManager.cpp.i
.PHONY : src/ControllerManager.i

# target to preprocess a source file
src/ControllerManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/ControllerManager.cpp.i
.PHONY : src/ControllerManager.cpp.i

src/ControllerManager.s: src/ControllerManager.cpp.s
.PHONY : src/ControllerManager.s

# target to generate assembly for a file
src/ControllerManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/ControllerManager.cpp.s
.PHONY : src/ControllerManager.cpp.s

src/Enemy.o: src/Enemy.cpp.o
.PHONY : src/Enemy.o

# target to build an object file
src/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Enemy.cpp.o
.PHONY : src/Enemy.cpp.o

src/Enemy.i: src/Enemy.cpp.i
.PHONY : src/Enemy.i

# target to preprocess a source file
src/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Enemy.cpp.i
.PHONY : src/Enemy.cpp.i

src/Enemy.s: src/Enemy.cpp.s
.PHONY : src/Enemy.s

# target to generate assembly for a file
src/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Enemy.cpp.s
.PHONY : src/Enemy.cpp.s

src/EnemyCyborg.o: src/EnemyCyborg.cpp.o
.PHONY : src/EnemyCyborg.o

# target to build an object file
src/EnemyCyborg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/EnemyCyborg.cpp.o
.PHONY : src/EnemyCyborg.cpp.o

src/EnemyCyborg.i: src/EnemyCyborg.cpp.i
.PHONY : src/EnemyCyborg.i

# target to preprocess a source file
src/EnemyCyborg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/EnemyCyborg.cpp.i
.PHONY : src/EnemyCyborg.cpp.i

src/EnemyCyborg.s: src/EnemyCyborg.cpp.s
.PHONY : src/EnemyCyborg.s

# target to generate assembly for a file
src/EnemyCyborg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/EnemyCyborg.cpp.s
.PHONY : src/EnemyCyborg.cpp.s

src/EnemySentients.o: src/EnemySentients.cpp.o
.PHONY : src/EnemySentients.o

# target to build an object file
src/EnemySentients.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/EnemySentients.cpp.o
.PHONY : src/EnemySentients.cpp.o

src/EnemySentients.i: src/EnemySentients.cpp.i
.PHONY : src/EnemySentients.i

# target to preprocess a source file
src/EnemySentients.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/EnemySentients.cpp.i
.PHONY : src/EnemySentients.cpp.i

src/EnemySentients.s: src/EnemySentients.cpp.s
.PHONY : src/EnemySentients.s

# target to generate assembly for a file
src/EnemySentients.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/EnemySentients.cpp.s
.PHONY : src/EnemySentients.cpp.s

src/Flamethrower.o: src/Flamethrower.cpp.o
.PHONY : src/Flamethrower.o

# target to build an object file
src/Flamethrower.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Flamethrower.cpp.o
.PHONY : src/Flamethrower.cpp.o

src/Flamethrower.i: src/Flamethrower.cpp.i
.PHONY : src/Flamethrower.i

# target to preprocess a source file
src/Flamethrower.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Flamethrower.cpp.i
.PHONY : src/Flamethrower.cpp.i

src/Flamethrower.s: src/Flamethrower.cpp.s
.PHONY : src/Flamethrower.s

# target to generate assembly for a file
src/Flamethrower.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Flamethrower.cpp.s
.PHONY : src/Flamethrower.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Health.o: src/Health.cpp.o
.PHONY : src/Health.o

# target to build an object file
src/Health.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Health.cpp.o
.PHONY : src/Health.cpp.o

src/Health.i: src/Health.cpp.i
.PHONY : src/Health.i

# target to preprocess a source file
src/Health.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Health.cpp.i
.PHONY : src/Health.cpp.i

src/Health.s: src/Health.cpp.s
.PHONY : src/Health.s

# target to generate assembly for a file
src/Health.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Health.cpp.s
.PHONY : src/Health.cpp.s

src/Laser.o: src/Laser.cpp.o
.PHONY : src/Laser.o

# target to build an object file
src/Laser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Laser.cpp.o
.PHONY : src/Laser.cpp.o

src/Laser.i: src/Laser.cpp.i
.PHONY : src/Laser.i

# target to preprocess a source file
src/Laser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Laser.cpp.i
.PHONY : src/Laser.cpp.i

src/Laser.s: src/Laser.cpp.s
.PHONY : src/Laser.s

# target to generate assembly for a file
src/Laser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Laser.cpp.s
.PHONY : src/Laser.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Score.o: src/Score.cpp.o
.PHONY : src/Score.o

# target to build an object file
src/Score.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Score.cpp.o
.PHONY : src/Score.cpp.o

src/Score.i: src/Score.cpp.i
.PHONY : src/Score.i

# target to preprocess a source file
src/Score.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Score.cpp.i
.PHONY : src/Score.cpp.i

src/Score.s: src/Score.cpp.s
.PHONY : src/Score.s

# target to generate assembly for a file
src/Score.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/Score.cpp.s
.PHONY : src/Score.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/qcustomplot.o: src/qcustomplot.cpp.o
.PHONY : src/qcustomplot.o

# target to build an object file
src/qcustomplot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/qcustomplot.cpp.o
.PHONY : src/qcustomplot.cpp.o

src/qcustomplot.i: src/qcustomplot.cpp.i
.PHONY : src/qcustomplot.i

# target to preprocess a source file
src/qcustomplot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/qcustomplot.cpp.i
.PHONY : src/qcustomplot.cpp.i

src/qcustomplot.s: src/qcustomplot.cpp.s
.PHONY : src/qcustomplot.s

# target to generate assembly for a file
src/qcustomplot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/qcustomplot.cpp.s
.PHONY : src/qcustomplot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SpaceInvaders_autogen"
	@echo "... SpaceInvaders_autogen_timestamp_deps"
	@echo "... SpaceInvaders"
	@echo "... SpaceInvaders_autogen/EWIEGA46WW/qrc_res.o"
	@echo "... SpaceInvaders_autogen/EWIEGA46WW/qrc_res.i"
	@echo "... SpaceInvaders_autogen/EWIEGA46WW/qrc_res.s"
	@echo "... SpaceInvaders_autogen/mocs_compilation.o"
	@echo "... SpaceInvaders_autogen/mocs_compilation.i"
	@echo "... SpaceInvaders_autogen/mocs_compilation.s"
	@echo "... src/AxisPlot.o"
	@echo "... src/AxisPlot.i"
	@echo "... src/AxisPlot.s"
	@echo "... src/Bullet.o"
	@echo "... src/Bullet.i"
	@echo "... src/Bullet.s"
	@echo "... src/ComboBoxTxt.o"
	@echo "... src/ComboBoxTxt.i"
	@echo "... src/ComboBoxTxt.s"
	@echo "... src/ControllerManager.o"
	@echo "... src/ControllerManager.i"
	@echo "... src/ControllerManager.s"
	@echo "... src/Enemy.o"
	@echo "... src/Enemy.i"
	@echo "... src/Enemy.s"
	@echo "... src/EnemyCyborg.o"
	@echo "... src/EnemyCyborg.i"
	@echo "... src/EnemyCyborg.s"
	@echo "... src/EnemySentients.o"
	@echo "... src/EnemySentients.i"
	@echo "... src/EnemySentients.s"
	@echo "... src/Flamethrower.o"
	@echo "... src/Flamethrower.i"
	@echo "... src/Flamethrower.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Health.o"
	@echo "... src/Health.i"
	@echo "... src/Health.s"
	@echo "... src/Laser.o"
	@echo "... src/Laser.i"
	@echo "... src/Laser.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Score.o"
	@echo "... src/Score.i"
	@echo "... src/Score.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/qcustomplot.o"
	@echo "... src/qcustomplot.i"
	@echo "... src/qcustomplot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

